FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet publish "web/<changeme>.csproj" -c Release -o /publish

FROM microsoft/dotnet:2.1-aspnetcore-runtime
ENV TRIPS_API_ENDPOINT="http://changeme.westus.cloudapp.azure.com" \
    USER_API_ENDPOINT="http://changeme.westus.cloudapp.azure.com"
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "<changeme>.dll"]